Repository elasticpath/react-pwa-reference-storefront, pull requests merged in 2018-11, with the labels that each got.

#96 Add dynamic cart item modifier inputs
  src/components/cart.lineitem.jsx
  src/components/productdisplayitem.main.jsx
  src/components/productdisplayitem.main.less
Labels: enhancement

#105 Fix for Issue 101
  src/components/checkout.summarylist.jsx
  src/containers/CheckoutPage.jsx
Labels: bug

#119 DB 89 tutorials
  _data/navigation.yml
  _layouts/master.html
  documentation/extending.md
  documentation/tutorial_creatingPages.md
  documentation/tutorial_setupProduction.md
  documentation/tutorial_siteBranding.md
  stylesheets/blue.css
  stylesheets/style.css
  stylesheets/stylesheet.css
Labels: docs
